# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GptQA',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/GptQA',
                'lib_path': 'GptQA'},
  'syms': {'GptQA.core': {'GptQA.core.foo': ('core.html#foo', 'GptQA/core.py')}}}
